name: EC2 Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        
    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Execute git pull on EC2
      run: |
        ssh ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd LR_CICD/
          git pull
        EOF 